# excel_io.py
import xlsxwriter
from xlsxwriter.utility import xl_rowcol_to_cell
from openpyxl import load_workbook
from utils import COURSE_COLORS

def load_courses_from_excel(path):
    """Load courses from an existing Excel file generated by this script."""
    print(f"Loading existing file: {path}")
    wb = load_workbook(path, data_only=False)
    ws = wb.active

    courses = []
    components_start_col = 6 

    # Determine max components by scanning header
    max_components = 0
    col = components_start_col
    while True:
        val = ws.cell(row=1, column=col).value
        if val is None or val == "":
            break
        max_components += 1
        col += 4

    row = 3
    while True:
        code = ws.cell(row=row, column=1).value
        if not code:
            break
        title = ws.cell(row=row, column=2).value
        credits = ws.cell(row=row, column=3).value

        components = []
        col_cursor = components_start_col
        for i in range(max_components):
            name_cell = ws.cell(row=1, column=col_cursor)
            weight_val = ws.cell(row=row, column=col_cursor + 3).value
            if weight_val is not None and float(weight_val) > 0:
                comp_name = name_cell.value or f"Component {i+1}"
                components.append({"name": str(comp_name), "weight": float(weight_val)})
            col_cursor += 4

        courses.append({
            "code": str(code),
            "title": str(title),
            "credits": float(credits),
            "components": components
        })
        row += 1

    print(f"Loaded {len(courses)} course(s) from file.\n")
    return courses

def create_excel(courses, filename):
    """Create the Excel workbook."""
    workbook = xlsxwriter.Workbook(filename)
    worksheet = workbook.add_worksheet("Grades")

    # --- Formats ---
    header_fmt = workbook.add_format({
        'bold': True,
        'align': 'center',
        'valign': 'vcenter',
        'bg_color': '#F4C842',  # gold-like
        'font_color': 'black',
        'border': 1
    })
    
    sub_header_fmt = workbook.add_format({
        'bold': True,
        'align': 'center',
        'bg_color': '#FFD966',  # lighter gold
        'font_color': 'black',
        'border': 1
    })

    hidden_fmt = workbook.add_format({
        'bg_color': '#000000',
        'font_color': '#000000',
        'border': 1
    })
    spi_fmt = workbook.add_format({
        'bold': True, 'align': 'left', 'border': 1, 'bg_color': '#D3D3D3'
    })

    total_col_idx = 3   # D
    grade_col_idx = 4   # E
    components_start_idx = 5  # F
    max_components = max((len(c['components']) for c in courses), default=0)

    # --- Headers ---
    row = 0
    worksheet.write(row, 0, "Course Code", header_fmt)
    worksheet.write(row, 1, "Course Title", header_fmt)
    worksheet.write(row, 2, "Credits", header_fmt)
    worksheet.write(row, total_col_idx, "Total Score", header_fmt)
    worksheet.write(row, grade_col_idx, "Final Grade", header_fmt)

    col_cursor = components_start_idx
    for i in range(max_components):
        comp_name = f"Component {i+1}"
        # Try to find a name from existing courses for this slot
        for course in courses:
            if i < len(course['components']):
                comp_name = course['components'][i]['name']
                break
        worksheet.merge_range(row, col_cursor, row, col_cursor+3, comp_name, header_fmt)
        col_cursor += 4

    row += 1
    # Sub-header row logic...
    worksheet.write(row, 0, "", sub_header_fmt)
    worksheet.write(row, 1, "", sub_header_fmt)
    worksheet.write(row, 2, "", sub_header_fmt)
    worksheet.write(row, total_col_idx, "", sub_header_fmt)
    worksheet.write(row, grade_col_idx, "", sub_header_fmt)

    col_cursor = components_start_idx
    for _ in range(max_components):
        worksheet.write(row, col_cursor, "Marks", sub_header_fmt)
        worksheet.write(row, col_cursor+1, "Out of", sub_header_fmt)
        worksheet.write(row, col_cursor+2, "% Score", sub_header_fmt)
        worksheet.write(row, col_cursor+3, "Weightage", sub_header_fmt)
        col_cursor += 4

    row += 1
    start_data_row = row

    # --- Data Rows ---
    for course_idx, course in enumerate(courses):
        course_color = COURSE_COLORS[course_idx % len(COURSE_COLORS)]
        
        # Per-row Formats
        read_only_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color})
        input_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color})
        weight_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color, 'color': 'blue'})
        total_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color, 'bold': True})

        worksheet.write(row, 0, course['code'], read_only_fmt)
        worksheet.write(row, 1, course['title'], read_only_fmt)
        worksheet.write(row, 2, course['credits'], read_only_fmt)

        col_cursor = components_start_idx
        score_cells = []

        for comp in course['components']:
            marks_cell = xl_rowcol_to_cell(row, col_cursor)
            outof_cell = xl_rowcol_to_cell(row, col_cursor+1)
            score_cell = xl_rowcol_to_cell(row, col_cursor+2)
            weight_cell = xl_rowcol_to_cell(row, col_cursor+3)

            worksheet.write(row, col_cursor, "", input_fmt)     # Marks
            worksheet.write(row, col_cursor+1, "", input_fmt)   # Out of

            formula = f'=IF({outof_cell}<>0, ({marks_cell}/{outof_cell})*{weight_cell}, 0)'
            worksheet.write_formula(score_cell, formula, read_only_fmt)
            worksheet.write(row, col_cursor+3, comp['weight'], weight_fmt)

            score_cells.append(score_cell)
            col_cursor += 4

        # Fill remaining slots with black
        for _ in range(len(course['components']), max_components):
            for _ in range(4):
                worksheet.write(row, col_cursor, "", hidden_fmt)
                col_cursor += 1

        if score_cells:
            total_formula = "=" + "+".join(score_cells)
            worksheet.write_formula(row, total_col_idx, total_formula, total_fmt)
        else:
            worksheet.write(row, total_col_idx, 0, total_fmt)

        worksheet.write(row, grade_col_idx, "", input_fmt)
        row += 1

    # --- SPI Calculation ---
    row += 2
    worksheet.write(row, 0, "SPI:", spi_fmt)

    if courses:
        first_course_row = start_data_row
        last_course_row = start_data_row + len(courses) - 1
        credits_range = f"C{first_course_row+1}:C{last_course_row+1}"
        grade_range = f"E{first_course_row+1}:E{last_course_row+1}"

        spi_formula = (
            f'=SUMPRODUCT(CHOOSE(IFERROR(MATCH({grade_range},'
            f'{{"A*","A","B+","B","C+","C","D","E","F"}},0),9),'
            f'10,10,9,8,7,6,5,0,0),{credits_range})/SUM({credits_range})'
        )
        worksheet.write_formula(row, 1, spi_formula, spi_fmt)

    # Layout
    worksheet.set_column('A:A', 12)   # Code
    worksheet.set_column('B:B', 30)   # Title
    worksheet.set_column('C:C', 8)    # Credits
    worksheet.set_column('D:E', 12)   # Total/Grade
    worksheet.set_column('F:Z', 12)   # Components
    worksheet.freeze_panes(2, 2)

    workbook.close()
    print(f"\nSuccess! '{filename}' created.")

