import sys
import os
import xlsxwriter
from xlsxwriter.utility import xl_rowcol_to_cell
from openpyxl import load_workbook

# --- Custom Exception for Flow Control ---
class ExitToMenu(Exception):
    """Raised when user wants to abort the current operation and return to main menu."""
    pass

# --- Color palette for courses ---
COURSE_COLORS = [
    '#E8F4F8',  # Light cyan
    '#F0E8F8',  # Light purple
    '#F8F0E8',  # Light orange
    '#E8F8E8',  # Light green
    '#F8E8E8',  # Light red
    '#F8F8E8',  # Light yellow
    '#E8F8F0',  # Light teal
    '#F8E8F0',  # Light pink
]

# ---------------- Generic input helper ----------------

def get_input(prompt, type_func=str, condition=lambda x: True,
              error_msg="Invalid input. Please try again."):
    """
    Prompt user for input, validate type/condition, and support 'exit' to return to main menu.
    """
    while True:
        raw = input(prompt).strip()
        if raw.lower() == 'exit':
            raise ExitToMenu()
        if not raw and type_func is str:
            if condition(raw):
                return raw
        try:
            val = type_func(raw)
            if condition(val):
                return val
            else:
                print(f"  Error: {error_msg}")
        except ValueError:
            print(f"  Error: Expected {type_func.__name__}, got '{raw}'.")

# ---------------- Course I/O ----------------

def collect_course_details(existing_data=None):
    """
    Interactively collect one course's configuration.
    """
    print(f"\n--- {'Editing' if existing_data else 'Adding New'} Course (Type 'exit' to cancel) ---")
    code = get_input("Course Number (e.g., CS360): ",
                     str, lambda x: len(x) > 0, "Cannot be empty")
    title = get_input("Course Title: ",
                      str, lambda x: len(x) > 0, "Cannot be empty").upper()
    credits = get_input("Credits: ", int,
                        lambda x: x > 0, "Credits must be positive")

    components = []

    std_fields = ["Attendance", "Project", "Mid Semester", "End Semester"]
    print("\n--- Component Weightages (Enter 0 to skip) ---")
    for field in std_fields:
        w = get_input(f"Weightage for {field}: ", float,
                      lambda x: x >= 0, "Must be non-negative")
        if w > 0:
            components.append({"name": field, "weight": w})

    iter_fields = [["Quiz", "Quizzes"], ["Assignment", "Assignments"]]
    for field, field_mul in iter_fields:
        w = get_input(f"Total Weightage for all {field_mul}: ", float,
                      lambda x: x >= 0, "Must be non-negative")
        if w > 0:
            count = get_input(f"  -> How many {field_mul}?: ", int,
                              lambda x: x > 0, "Count must be at least 1")
            per_item_weight = w / count
            for i in range(1, count + 1):
                components.append({"name": f"{field} {i}",
                                   "weight": per_item_weight})

    print("\n--- Custom Components (Enter 0 weight to finish) ---")
    while True:
        try:
            w = get_input("Weightage for Other/Custom Component: ", float,
                          lambda x: x >= 0, "Must be non-negative")
        except ExitToMenu:
            raise
        if w == 0:
            break
        name = get_input("  -> Name of this component (e.g., 'Lab Exam'): ",
                         str, lambda x: len(x) > 0, "Name cannot be empty")
        components.append({"name": name, "weight": w})
        print(f"     (Added '{name}' with weight {w})")

    return {"code": code, "title": title, "credits": credits,
            "components": components}

def print_summary(courses):
    print("\n" + "="*40)
    print(f"Current List ({len(courses)} courses)")
    print("="*40)
    if not courses:
        print("  (No courses added yet)")
    for idx, c in enumerate(courses):
        comps = ", ".join([x['name'] for x in c['components']])
        print(f"  [{idx+1}] {c['code']} - {c['title']} ({c['credits']} cr)")
        print(f"      Components: {comps}")
    print("="*40)

# ---------------- Excel read ----------------

def load_courses_from_excel(path):
    """
    Load courses from an existing Excel file generated by this script.
    """
    print(f"Loading existing file: {path}")
    wb = load_workbook(path, data_only=False)
    ws = wb.active

    courses = []
    components_start_col = 6 

    max_components = 0
    col = components_start_col
    while True:
        val = ws.cell(row=1, column=col).value
        if val is None or val == "":
            break
        max_components += 1
        col += 4

    row = 3
    while True:
        code = ws.cell(row=row, column=1).value
        if not code:
            break
        title = ws.cell(row=row, column=2).value
        credits = ws.cell(row=row, column=3).value

        components = []
        col_cursor = components_start_col
        for i in range(max_components):
            name_cell = ws.cell(row=1, column=col_cursor)
            weight_val = ws.cell(row=row, column=col_cursor + 3).value
            if weight_val is not None and float(weight_val) > 0:
                comp_name = name_cell.value or f"Component {i+1}"
                components.append({"name": str(comp_name), "weight": float(weight_val)})
            col_cursor += 4

        courses.append({
            "code": str(code),
            "title": str(title),
            "credits": float(credits),
            "components": components
        })
        row += 1

    print(f"Loaded {len(courses)} course(s) from file.\n")
    return courses

# ---------------- Excel write ----------------

def create_excel(courses, filename):
    """
    Create the Excel workbook.
    """
    workbook = xlsxwriter.Workbook(filename)
    worksheet = workbook.add_worksheet("Grades")

    header_fmt = workbook.add_format({
        'bold': True, 'align': 'center', 'valign': 'vcenter',
        'bg_color': '#1e768f', 'font_color': 'white', 'border': 1
    })
    sub_header_fmt = workbook.add_format({
        'bold': True, 'align': 'center',
        'bg_color': '#2a9cb8', 'font_color': 'white', 'border': 1
    })
    hidden_fmt = workbook.add_format({'bg_color': '000000', 'font_color': '000000', 'border': 1})

    spi_fmt = workbook.add_format({
        'bold': True, 'align': 'left', 'border': 1,
        'bg_color': '#D3D3D3'
    })

    total_col_idx = 3   # D
    grade_col_idx = 4   # E
    components_start_idx = 5  # F
    max_components = max((len(c['components']) for c in courses), default=0)

    row = 0
    worksheet.write(row, 0, "Course Code", header_fmt)
    worksheet.write(row, 1, "Course Title", header_fmt)
    worksheet.write(row, 2, "Credits", header_fmt)
    worksheet.write(row, total_col_idx, "Total Score", header_fmt)
    worksheet.write(row, grade_col_idx, "Final Grade", header_fmt)

    col_cursor = components_start_idx
    for i in range(max_components):
        comp_name = f"Component {i+1}"
        for course in courses:
            if i < len(course['components']):
                comp_name = course['components'][i]['name']
                break
        worksheet.merge_range(row, col_cursor, row, col_cursor+3, comp_name, header_fmt)
        col_cursor += 4

    row += 1
    worksheet.write(row, 0, "", sub_header_fmt)
    worksheet.write(row, 1, "", sub_header_fmt)
    worksheet.write(row, 2, "", sub_header_fmt)
    worksheet.write(row, total_col_idx, "", sub_header_fmt)
    worksheet.write(row, grade_col_idx, "", sub_header_fmt)

    col_cursor = components_start_idx
    for _ in range(max_components):
        worksheet.write(row, col_cursor, "Marks", sub_header_fmt)
        worksheet.write(row, col_cursor+1, "Out of", sub_header_fmt)
        worksheet.write(row, col_cursor+2, "% Score", sub_header_fmt)
        worksheet.write(row, col_cursor+3, "Weightage", sub_header_fmt)
        col_cursor += 4

    row += 1
    start_data_row = row

    for course_idx, course in enumerate(courses):
        course_color = COURSE_COLORS[course_idx % len(COURSE_COLORS)]


        read_only_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color})

        input_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color})

        weight_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color, 'color': 'blue'})

        total_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color, 'bold': True})

        grade_input_fmt = workbook.add_format({'align': 'left', 'border': 1, 'bg_color': course_color})

        worksheet.write(row, 0, course['code'], read_only_fmt)
        worksheet.write(row, 1, course['title'], read_only_fmt)
        worksheet.write(row, 2, course['credits'], read_only_fmt)

        col_cursor = components_start_idx
        score_cells = []

        for comp in course['components']:
            marks_cell = xl_rowcol_to_cell(row, col_cursor)
            outof_cell = xl_rowcol_to_cell(row, col_cursor+1)
            score_cell = xl_rowcol_to_cell(row, col_cursor+2)
            weight_cell = xl_rowcol_to_cell(row, col_cursor+3)

            worksheet.write(row, col_cursor, "", input_fmt)     # Marks
            worksheet.write(row, col_cursor+1, "", input_fmt)   # Out of

            formula = f'=IF({outof_cell}<>0, ({marks_cell}/{outof_cell})*{weight_cell}, 0)'
            worksheet.write_formula(score_cell, formula, read_only_fmt)

            worksheet.write(row, col_cursor+3, comp['weight'], weight_fmt)

            score_cells.append(score_cell)
            col_cursor += 4

        for _ in range(len(course['components']), max_components):
            for _ in range(4):
                worksheet.write(row, col_cursor, "", hidden_fmt)
                col_cursor += 1

        if score_cells:
            total_formula = "=" + "+".join(score_cells)
            worksheet.write_formula(row, total_col_idx, total_formula, total_fmt)
        else:
            worksheet.write(row, total_col_idx, 0, total_fmt)

        worksheet.write(row, grade_col_idx, "", grade_input_fmt)

        row += 1

    row += 2
    worksheet.write(row, 0, "SPI:", spi_fmt)

    if courses:
        first_course_row = start_data_row
        last_course_row = start_data_row + len(courses) - 1
        credits_range = f"C{first_course_row+1}:C{last_course_row+1}"
        grade_range = f"E{first_course_row+1}:E{last_course_row+1}"

        spi_formula = (
            f'=SUMPRODUCT(CHOOSE(IFERROR(MATCH({grade_range},'
            f'{{"A*","A","B+","B","C+","C","D","E","F"}},0),9),'
            f'10,10,9,8,7,6,5,0,0),{credits_range})/SUM({credits_range})'
        )
        worksheet.write_formula(row, 1, spi_formula, spi_fmt)

    worksheet.set_column('A:A', 12)   # Code
    worksheet.set_column('B:B', 30)   # Title
    worksheet.set_column('C:C', 8)    # Credits
    worksheet.set_column('D:D', 12)   # Total
    worksheet.set_column('E:E', 12)   # Grade
    worksheet.set_column('F:Z', 12)   # Components
    worksheet.freeze_panes(2, 2)      # Freeze first 2 rows and A,B

    workbook.close()
    print(f"\nSuccess! '{filename}' created.")

# ---------------- Main menu ----------------

def main_menu(initial_courses, default_path):
    courses = initial_courses[:]
    while True:
        try:
            print_summary(courses)
            print("\nOptions:")
            print("  [A] Add a course")
            if courses:
                print("  [E] Edit a course")
                print("  [D] Delete a course")
                print("  [G] Generate Excel File")
            print("  [Q] Quit (without overwriting)")

            choice = get_input("\nSelect Option (type 'exit' anytime to reset current action): ", str).upper()

            if choice == 'A':
                try:
                    courses.append(collect_course_details())
                except ExitToMenu:
                    print("\n[!] Add cancelled. Returning to menu.")
                    continue

            elif choice == 'E' and courses:
                try:
                    idx = get_input("Enter number of course to edit: ", int,
                                    lambda x: 1 <= x <= len(courses),
                                    "Invalid number")
                    print(f"Editing Course #{idx}...")
                    courses[idx-1] = collect_course_details(courses[idx-1])
                except ExitToMenu:
                    print("\n[!] Edit cancelled. Returning to menu.")
                    continue

            elif choice == 'D' and courses:
                try:
                    idx = get_input("Enter number of course to delete: ", int,
                                    lambda x: 1 <= x <= len(courses),
                                    "Invalid number")
                    confirm = get_input(
                        f"Delete {courses[idx-1]['code']}? (y/n): ", str).lower()
                    if confirm == 'y':
                        del courses[idx-1]
                except ExitToMenu:
                    print("\n[!] Delete cancelled. Returning to menu.")
                    continue

            elif choice == 'G' and courses:
                try:
                    filename = get_input(
                        f"Enter filename (default: {default_path}): ", str)
                    if not filename:
                        filename = default_path
                    if not filename.endswith(".xlsx"):
                        filename += ".xlsx"
                    create_excel(courses, filename)
                    break
                except ExitToMenu:
                    print("\n[!] Generation cancelled. Returning to menu.")
                    continue

            elif choice == 'Q':
                print("Exiting without generating.")
                break

            else:
                print("Invalid option.")

        except ExitToMenu:
            print("\n(Already at main menu)")
            continue

if __name__ == "__main__":
    try:
        path = "grades.xlsx"
        if len(sys.argv) > 1:
            path = sys.argv[1]

        initial_courses = []
        if os.path.exists(path):
            try:
                initial_courses = load_courses_from_excel(path)
            except Exception as e:
                print(f"Warning: could not load '{path}', starting fresh. ({e})")

        main_menu(initial_courses, path)

    except KeyboardInterrupt:
        print("\nCancelled by user.")

